import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';

// PostgreSQL engine in memory. Auth/storage are minimal fixtures, not remote services.
test('church isolation, roles, capacity and cross-tenant references', async () => {
  const db = new PGlite();
  const migration = prefix => readFileSync(`supabase/migrations/${readdirSync('supabase/migrations').find(f => f.startsWith(prefix))}`, 'utf8');
  const exec = sql => db.exec(sql);
  const scalar = async sql => Object.values((await db.query(sql)).rows[0])[0];
  const uid = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
  const login = async n => exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub','${uid(n)}',false); SET ROLE authenticated;`);
  const root = () => exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub','',false);`);
  try {
    await exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
      CREATE SCHEMA auth; CREATE SCHEMA storage;
      CREATE TABLE auth.users(id uuid PRIMARY KEY, email text, email_confirmed_at timestamptz, raw_user_meta_data jsonb DEFAULT '{}');
      CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      CREATE TABLE storage.objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), bucket_id text, name text);
      ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
      GRANT USAGE ON SCHEMA public, auth, storage TO authenticated, anon, service_role;`);
    await exec(migration('20251209144023'));
    // Historical helpers and tables relevant to the migration under test.
    await exec(migration('20251210025623'));
    await exec(migration('20251210145428'));
    await exec(migration('20251211182915'));
    await exec(migration('20260522061316'));
    await exec(migration('20260811063212'));
    await exec(migration('20260723121703'));
    for (const prefix of ['20260210040834','20260314031319','20260326055624','20260606045029','20260727055509']) {
      const sql = migration(prefix);
      // Tables only: old RLS gets replaced by the new migration.
      for (const stmt of sql.match(/CREATE TABLE[\s\S]*?\);/g) ?? []) await exec(stmt.replace("encode(gen_random_bytes(32), 'hex')", "gen_random_uuid()::text"));
    }
    await exec(migration('20260812083206').split('GRANT SELECT')[0]);
    await exec(`CREATE TABLE public.recurring_schedules(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), church_id uuid NOT NULL REFERENCES churches(id), ministry_id uuid NOT NULL REFERENCES ministries(id), user_id uuid NOT NULL, role_id uuid REFERENCES ministry_roles(id));
      ALTER TABLE schedule_assignments ADD COLUMN checked_in_at timestamptz, ADD COLUMN checked_in_by uuid;
      CREATE FUNCTION public.apply_recurring_assignments(uuid) RETURNS integer LANGUAGE sql AS $$ SELECT 0 $$;
      DO $$ DECLARE t record; BEGIN FOR t IN SELECT tablename FROM pg_tables WHERE schemaname='public' LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t.tablename); END LOOP; END $$;
      GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated, service_role;
      INSERT INTO auth.users(id,email,email_confirmed_at) VALUES ('${uid(1)}','tiagotalmud@gmail.com',now());`);
    for (let n = 2; n <= 9; n++) await exec(`INSERT INTO auth.users(id,email,email_confirmed_at) VALUES ('${uid(n)}','user${n}@example.test',now())`);
    await exec(migration('20260925120000'));
    await exec(migration('20260925130000'));
    await exec(migration('20260915140000'));
    await exec(`ALTER TABLE profiles ADD COLUMN must_change_password boolean NOT NULL DEFAULT false`);
    await exec(migration('20260925140000'));
    await exec(migration('20260925150000'));
    await login(2);
    const a = await scalar(`SELECT create_church('Church A')`);
    assert.equal(await scalar(`SELECT max_users FROM church_subscriptions WHERE church_id='${a}'`), 3);
    assert.equal(await scalar(`SELECT role FROM church_members WHERE user_id='${uid(2)}'`), 'admin');
    await login(3);
    const b = await scalar(`SELECT create_church('Church B')`);
    await login(2);
    assert.equal(await scalar(`SELECT count(*) FROM churches WHERE id='${b}'`), 0);
    assert.equal(await scalar(`SELECT count(*) FROM profiles WHERE id='${uid(3)}'`), 0);
    await assert.rejects(exec(`INSERT INTO church_members(church_id,user_id,role) VALUES ('${b}','${uid(2)}','admin')`), /row-level security/);
    await exec(`UPDATE church_subscriptions SET plan='basic',max_users=10 WHERE church_id='${a}'`);
    assert.equal(await scalar(`SELECT max_users FROM church_subscriptions WHERE church_id='${a}'`), 3);
    await assert.rejects(exec(`INSERT INTO church_members(church_id,user_id,role) VALUES ('${a}','${uid(3)}','volunteer')`), /row-level security/);
    await root();
    await exec(`SET ROLE service_role; INSERT INTO church_members(church_id,user_id,role) VALUES ('${a}','${uid(4)}','ministry_leader'),('${a}','${uid(5)}','volunteer')`);
    await assert.rejects(exec(`INSERT INTO church_members(church_id,user_id) VALUES ('${a}','${uid(6)}')`), /Limite de usuários/);
    await login(2);
    const ma = await scalar(`INSERT INTO ministries(church_id,name) VALUES ('${a}','Music A') RETURNING id`);
    await login(3);
    const mb = await scalar(`INSERT INTO ministries(church_id,name) VALUES ('${b}','Music B') RETURNING id`);
    const eb = await scalar(`INSERT INTO events(church_id,title,event_date,start_time) VALUES ('${b}','Event B','2026-10-01','10:00') RETURNING id`);
    await login(2);
    await assert.rejects(exec(`INSERT INTO schedules(event_id,ministry_id) VALUES ('${eb}','${ma}')`), /igrejas diferentes/);
    await assert.rejects(exec(`INSERT INTO ministry_members(ministry_id,user_id) VALUES ('${ma}','${uid(3)}')`), /não pertence/);
    await assert.rejects(exec(`UPDATE ministries SET church_id='${b}' WHERE id='${ma}'`), /não pode ser alterada/);
    await exec(`INSERT INTO ministry_members(ministry_id,user_id,is_leader) VALUES ('${ma}','${uid(4)}',true),('${ma}','${uid(5)}',false)`);
    await login(4);
    const ea = await scalar(`INSERT INTO events(church_id,title,event_date,start_time) VALUES ('${a}','Event A','2026-10-01','10:00') RETURNING id`);
    await assert.rejects(exec(`SELECT set_member_role('${uid(5)}','${a}','admin')`), /Sem permissão/);
    await assert.rejects(exec(`INSERT INTO events(church_id,title,event_date,start_time) VALUES ('${b}','Intrusion','2026-10-01','10:00')`), /row-level security/);
    const schedule = await scalar(`INSERT INTO schedules(event_id,ministry_id) VALUES ('${ea}','${ma}') RETURNING id`);
    const assignment = await scalar(`INSERT INTO schedule_assignments(schedule_id,user_id) VALUES ('${schedule}','${uid(5)}') RETURNING id`);
    await login(5);
    await assert.rejects(exec(`INSERT INTO events(church_id,title,event_date,start_time) VALUES ('${a}','Intrusion','2026-10-01','10:00')`), /row-level security/);
    await exec(`UPDATE schedule_assignments SET status='confirmed' WHERE id='${assignment}'`);
    assert.equal(await scalar(`SELECT status FROM schedule_assignments WHERE id='${assignment}'`), 'confirmed');
    await assert.rejects(exec(`UPDATE schedule_assignments SET role_id=gen_random_uuid() WHERE id='${assignment}'`));
    const swap = await scalar(`INSERT INTO swap_requests(schedule_id,requester_assignment_id,requester_id,requested_id) VALUES ('${schedule}','${assignment}','${uid(5)}','${uid(4)}') RETURNING id`);
    await assert.rejects(exec(`SELECT respond_to_swap('${swap}',true)`), /Troca indisponível/);
    await login(4);
    await exec(`SELECT respond_to_swap('${swap}',true)`);
    assert.equal(await scalar(`SELECT user_id FROM schedule_assignments WHERE id='${assignment}'`), uid(4));
    await assert.rejects(exec(`SELECT respond_to_swap('${swap}',true)`), /Troca indisponível/);
    await login(1);
    assert.equal(await scalar(`SELECT is_super_admin()`), true);
    assert.equal(await scalar(`SELECT count(*) FROM churches`), 2);
    await assert.rejects(exec(`INSERT INTO church_members(church_id,user_id) VALUES ('${a}','${uid(6)}')`), /Limite de usuários/);
    await exec(`UPDATE church_subscriptions SET plan='basic',max_users=10 WHERE church_id='${a}'`);
    await root();
    await exec(`SET ROLE service_role`);
    await exec(`INSERT INTO church_members(church_id,user_id) VALUES ('${a}','${uid(6)}')`);
    await login(2);
    assert.equal(await scalar(`SELECT count(*) FROM church_members WHERE church_id='${a}'`), 4);
    await assert.rejects(exec(`INSERT INTO platform_admin(user_id) VALUES ('${uid(2)}')`), /permission denied/);
    await root();
    await assert.rejects(exec(`INSERT INTO platform_admin(user_id) VALUES ('${uid(2)}')`), /duplicate key/);
    // Service-role writes must also obey capacity.
    await exec(`UPDATE church_subscriptions SET plan='free',max_users=3 WHERE church_id='${a}'; SET ROLE service_role;`);
    await assert.rejects(exec(`INSERT INTO church_members(church_id,user_id) VALUES ('${a}','${uid(7)}')`), /Limite de usuários/);
    await root();
    // Regression: an unlimited plan with a stale max_users=3 must accept users beyond three.
    await exec(`UPDATE church_subscriptions SET plan='unlimited',max_users=3,status='active' WHERE church_id='${a}'`);
    await login(2);
    const unlimited = await scalar(`SELECT get_church_subscription('${a}')`);
    assert.equal(unlimited.plan, 'unlimited');
    assert.equal(unlimited.is_unlimited, true);
    assert.equal(unlimited.max_users, null);
    assert.equal(unlimited.can_add_users, true);
    await assert.rejects(exec(`SELECT get_church_subscription('${b}')`), /Sem permissão/);
    await root();
    await exec(`SET ROLE service_role; INSERT INTO church_members(church_id,user_id,role) VALUES
      ('${a}','${uid(7)}','volunteer'),('${a}','${uid(8)}','ministry_leader'),('${a}','${uid(9)}','volunteer')`);
    const otherMinistry = await scalar(`INSERT INTO ministries(church_id,name) VALUES ('${a}','Other ministry') RETURNING id`);
    await exec(`INSERT INTO ministry_members(ministry_id,user_id,is_leader) VALUES
      ('${otherMinistry}','${uid(8)}',true),('${otherMinistry}','${uid(6)}',false),
      ('${otherMinistry}','${uid(4)}',false),('${ma}','${uid(2)}',false)`);
    await login(4);
    assert.equal(await scalar(`SELECT count(*) FROM church_members WHERE church_id='${a}' AND role='volunteer'`), 1);
    assert.equal(await scalar(`SELECT count(*) FROM profiles WHERE id='${uid(6)}'`), 0);
    assert.equal(await scalar(`SELECT count(*) FROM profiles WHERE id='${uid(2)}'`), 0);
    assert.equal(await scalar(`SELECT count(*) FROM list_safe_profiles() WHERE id='${uid(6)}'`), 0);
    assert.equal(await scalar(`SELECT count(*) FROM list_safe_profiles() WHERE id='${uid(5)}'`), 1);
    await exec(`UPDATE profiles SET full_name='Forbidden' WHERE id='${uid(5)}';
      DELETE FROM church_members WHERE user_id='${uid(5)}' AND church_id='${a}';
      DELETE FROM ministry_members WHERE user_id='${uid(5)}' AND ministry_id='${ma}';
      UPDATE ministry_members SET is_leader=true WHERE user_id='${uid(4)}' AND ministry_id='${otherMinistry}';`);
    await assert.rejects(exec(`INSERT INTO ministry_members(ministry_id,user_id) VALUES ('${ma}','${uid(9)}')`), /row-level security/);
    await login(2);
    assert.notEqual(await scalar(`SELECT full_name FROM profiles WHERE id='${uid(5)}'`), 'Forbidden');
    assert.equal(await scalar(`SELECT count(*) FROM church_members WHERE church_id='${a}' AND user_id='${uid(5)}'`), 1);
    assert.equal(await scalar(`SELECT count(*) FROM ministry_members WHERE ministry_id='${ma}' AND user_id='${uid(5)}'`), 1);
    assert.equal(await scalar(`SELECT is_leader FROM ministry_members WHERE ministry_id='${otherMinistry}' AND user_id='${uid(4)}'`), false);
    await exec(`UPDATE ministry_members SET is_leader=false WHERE ministry_id='${ma}' AND user_id='${uid(4)}'`);
    await login(4);
    assert.equal(await scalar(`SELECT count(*) FROM church_members WHERE church_id='${a}' AND role='volunteer'`), 0);
    assert.equal(await scalar(`SELECT count(*) FROM profiles WHERE id='${uid(5)}'`), 0);
    await login(2);
    await exec(`UPDATE ministry_members SET is_leader=true WHERE ministry_id='${ma}' AND user_id='${uid(4)}'`);
    await root();
    await exec(`INSERT INTO auth.users(id,email,email_confirmed_at) VALUES ('${uid(10)}','new@example.test',now());
      INSERT INTO ministry_members(ministry_id,user_id) VALUES ('${otherMinistry}','${uid(5)}')`);
    await login(4);
    assert.equal(await scalar(`SELECT can_create_church_user('${a}','volunteer',ARRAY['${ma}']::uuid[])`), true);
    for (const [role, teams] of [['admin', [ma]], ['volunteer', []], ['volunteer', [otherMinistry]], ['volunteer', [ma, mb]]]) {
      assert.equal(await scalar(`SELECT can_create_church_user('${a}','${role}',ARRAY[${teams.map(id => `'${id}'`).join(',')}]::uuid[])`), false);
    }
    await assert.rejects(exec(`SELECT provision_church_user('${uid(4)}','${uid(10)}','${a}','volunteer',ARRAY['${ma}']::uuid[])`), /permission denied/);
    for (const target of [2, 6, 8]) {
      await assert.rejects(exec(`SELECT edit_team_user('${uid(target)}','${a}','Denied')`), /Sem permiss/);
      await assert.rejects(exec(`SELECT remove_team_user('${uid(target)}','${a}')`), /Sem permiss/);
    }
    await exec(`SELECT edit_team_user('${uid(5)}','${a}','Updated name')`);
    assert.equal(await scalar(`SELECT full_name FROM profiles WHERE id='${uid(5)}'`), 'Updated name');
    await exec(`SELECT remove_team_user('${uid(5)}','${a}')`);
    assert.equal(await scalar(`SELECT can_manage_team_user('${uid(5)}','${a}')`), false);
    await root();
    assert.equal(await scalar(`SELECT count(*) FROM ministry_members WHERE user_id='${uid(5)}' AND ministry_id='${otherMinistry}'`), 1);
    assert.equal(await scalar(`SELECT count(*) FROM church_members WHERE user_id='${uid(5)}' AND church_id='${a}'`), 1);
    await exec(`SET ROLE service_role`);
    await assert.rejects(exec(`SELECT provision_church_user('${uid(4)}','${uid(10)}','${a}','admin',ARRAY['${ma}']::uuid[])`), /Sem permiss/);
    await exec(`SELECT provision_church_user('${uid(4)}','${uid(10)}','${a}','volunteer',ARRAY['${ma}']::uuid[])`);
    assert.equal(await scalar(`SELECT count(*) FROM ministry_members WHERE user_id='${uid(10)}' AND ministry_id='${ma}' AND NOT is_leader`), 1);
    assert.equal(await scalar(`SELECT must_change_password FROM profiles WHERE id='${uid(10)}'`), true);
    await root();
    await exec(`UPDATE church_subscriptions SET status='canceled' WHERE church_id='${a}'`);
    await login(2);
    const canceled = await scalar(`SELECT get_church_subscription('${a}')`);
    assert.equal(canceled.is_unlimited, false);
    assert.equal(canceled.can_add_users, false);
    assert.equal(canceled.max_users, 3);
    await login(2);
    await assert.rejects(exec(`SELECT delete_church_account('${a}','Church A')`), /permission denied/);
    await root();
    await exec(`INSERT INTO schedule_role_quotas(schedule_id,quantity) VALUES ('${schedule}',2);
      UPDATE church_subscriptions SET stripe_customer_id='cus_test' WHERE church_id='${a}'; SET ROLE service_role;`);
    await assert.rejects(exec(`SELECT delete_church_account('${a}','Wrong name')`), /nome da igreja/);
    await assert.rejects(exec(`SELECT delete_church_account('${a}','Church A')`), /Stripe/);
    assert.equal(await scalar(`SELECT count(*) FROM schedule_role_quotas WHERE schedule_id='${schedule}'`), 1);
    await exec(`UPDATE church_subscriptions SET stripe_customer_id=NULL WHERE church_id='${a}';
      SELECT delete_church_account('${a}','Church A')`);
    assert.equal(await scalar(`SELECT count(*) FROM churches WHERE id='${a}'`), 0);
    assert.equal(await scalar(`SELECT count(*) FROM church_subscriptions WHERE church_id='${a}'`), 0);
    assert.equal(await scalar(`SELECT count(*) FROM church_members WHERE church_id='${a}'`), 0);
    assert.equal(await scalar(`SELECT count(*) FROM ministries WHERE church_id='${a}'`), 0);
    assert.equal(await scalar(`SELECT count(*) FROM schedule_role_quotas WHERE schedule_id='${schedule}'`), 0);
    assert.equal(await scalar(`SELECT count(*) FROM churches WHERE id='${b}'`), 1);
    assert.equal(await scalar(`SELECT count(*) FROM ministries WHERE id='${mb}'`), 1);
    await root();
    assert.equal(await scalar(`SELECT count(*) FROM auth.users WHERE id='${uid(2)}'`), 1);
    assert.equal(await scalar(`SELECT count(*) FROM platform_admin`), 1);
  } finally { await db.close(); }
});
